# Generated by Django 3.2 on 2021-04-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_file',
            field=models.FileField(blank=True, upload_to='book_files'),
        ),
    ]
